on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.x", "1.23.x", "1.24.x"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - run: make test
